from custom_gym.classic_control.MassPointGoal import MassPointGoalEnv
from custom_gym.classic_control.MassPointGoalInstr import MassPointGoalInstrEnv
from custom_gym.classic_control.MassPointGoalAction import MassPointGoalActionEnv

from custom_gym.classic_control.MassPointTraj import MassPointTrajEnv
from custom_gym.classic_control.MassPointTrajInstr import MassPointTrajInstrEnv
from custom_gym.classic_control.MassPointTrajAction import MassPointTrajActionEnv

from custom_gym.classic_control.MassPointGoal_v1 import MassPointGoalEnv_v1
from custom_gym.classic_control.MassPointGoalInstr_v1 import MassPointGoalInstrEnv_v1
from custom_gym.classic_control.MassPointGoalAction_v1 import MassPointGoalActionEnv_v1

from custom_gym.classic_control.MassPointTraj_v1 import MassPointTrajEnv_v1
from custom_gym.classic_control.MassPointTrajInstr_v1 import MassPointTrajInstrEnv_v1
from custom_gym.classic_control.MassPointTrajAction_v1 import MassPointTrajActionEnv_v1

