from custom_gym.classic_control.mountain_car import MountainCarEnv
from custom_gym.classic_control.mass_point import MassPointEnv

from custom_gym.classic_control.mass_point_v1 import MassPointEnv_v1
from custom_gym.classic_control.mass_point_gep import MassPointGEPEnv
from custom_gym.classic_control.five_target import FiveTargetEnv
from custom_gym.classic_control.five_target_v1 import FiveTargetEnv_v1
from custom_gym.classic_control.five_target_v2 import FiveTargetEnv_v2
from custom_gym.classic_control.five_target_color import FiveTargetColorEnv
from custom_gym.classic_control.five_target_color_random_face import FiveTargetColorV1Env
from custom_gym.classic_control.five_target_random_color import FiveTargetRandColorEnv
from custom_gym.classic_control.five_target_random_color_v2 import FiveTargetRandColorEnv_v2
from custom_gym.classic_control.over_cooked import OverCookedEnv
from custom_gym.classic_control.over_cooked_v1 import OverCookedEnv_v1
