from custom_gym.classic_control.MassPointGoal import MassPointGoalEnv
from custom_gym.classic_control.MassPointGoalInstr import MassPointGoalInstrEnv
from custom_gym.classic_control.MassPointGoalAction import MassPointGoalActionEnv

from custom_gym.classic_control.MassPointTraj import MassPointTrajEnv
from custom_gym.classic_control.MassPointTrajInstr import MassPointTrajInstrEnv
from custom_gym.classic_control.MassPointTrajAction import MassPointTrajActionEnv
